spring:
  application:
    name: jpa_with_sanity
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/libary
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect